# settings.example.yml
# This is the settings for for STD (Service Tracker Dashboard)
# Any ENV variables set will be used before the entry in this config file.

# Backup file location.   Make sure this is mountable in from your container.  
# Can be set with ENV BACKUP_PATH=/config/backups
backup_path: /config/backups
backup_days_to_keep: 7

# API Token for connections
# Can be set with ENV API_TOKEN=supersecrettoken
api_token: supersecrettoken

# URL for dozzle instance for quick connect to logs
# Can be set with ENV STD_DOZZLE_URL
# If you set this a tools section will show up in your
# dashboard. 
#std_dozzle_url: http://dozzle.host.com:8080

# How often do we test the URL endpoints
url_refresh_interval: 300

# How often do we reload the widget data default 300 seconds
widget_background_reload: 900

# how long to default the user session, default is 120 minutes
# can be set as USER_SESSION_LENGTH in ENV
user_session_length: 120
